### ISSUE TITLE
"make all" removes ansible.deb but doesn't install a new one

### ISSUE THREAD

**Issue by ieguiguren** [iancleary/ansible-desktop#164]
System: Ubuntu 20.04 just installed today

I've inserted the sudo password in previous runs of the script so it is not asked during this one. I've bolded the lines related to the error. 

$ make all
Makefile:45: ANSIBLE is ansible-galaxy install -r requirements.yml && ansible-playbook personal_computer.yml -v -i ".inventory" -l octopussy -e '{"users": [{"username": "xir"}]}' --ask-become-pass
\# Ensure chosen hostname is present in group_vars and .inventory folder
bash scripts/setup_inventory_and_group_vars.sh
\# Apt Dependencies (removes apt ansible)
bash scripts/before_install_apt_dependencies.sh
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  ieee-data python3-argcomplete python3-dnspython python3-jinja2 python3-jmespath python3-kerberos python3-libcloud python3-lockfile
  python3-markupsafe python3-netaddr python3-ntlm-auth python3-requests-kerberos python3-requests-ntlm python3-selinux python3-winrm
  python3-xmltodict
Utilice «sudo apt autoremove» para eliminarlos.
**Los siguientes paquetes se ELIMINARÁN:
  ansible**
0 actualizados, 0 nuevos se instalarán, 1 para eliminar y 0 no actualizados.
Se liberarán 58,0 MB después de esta operación.
(Leyendo la base de datos ... 181361 ficheros o directorios instalados actualmente.)
Desinstalando ansible (2.9.6+dfsg-1) ...
Procesando disparadores para man-db (2.9.1-1) ...
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Los siguientes paquetes se ELIMINARÁN:
  ieee-data python3-argcomplete python3-dnspython python3-jinja2 python3-jmespath python3-kerberos python3-libcloud python3-lockfile
  python3-markupsafe python3-netaddr python3-ntlm-auth python3-requests-kerberos python3-requests-ntlm python3-selinux python3-winrm
  python3-xmltodict
0 actualizados, 0 nuevos se instalarán, 16 para eliminar y 0 no actualizados.
Se liberarán 31,2 MB después de esta operación.
(Leyendo la base de datos ... 175234 ficheros o directorios instalados actualmente.)
Desinstalando python3-netaddr (0.7.19-3) ...
Desinstalando ieee-data (20180805.1) ...
Desinstalando python3-argcomplete (1.8.1-1.3ubuntu1) ...
Desinstalando python3-dnspython (1.16.0-1build1) ...
Desinstalando python3-jinja2 (2.10.1-2) ...
Desinstalando python3-jmespath (0.9.4-2) ...
Desinstalando python3-requests-kerberos (0.12.0-2) ...
Desinstalando python3-kerberos (1.1.14-3.1build1) ...
Desinstalando python3-libcloud (2.8.0-1) ...
Desinstalando python3-lockfile (1:0.12.2-2ubuntu2) ...
Desinstalando python3-markupsafe (1.1.0-1build2) ...
Desinstalando python3-winrm (0.3.0-2) ...
Desinstalando python3-requests-ntlm (1.1.0-1) ...
Desinstalando python3-ntlm-auth (1.1.0-1) ...
Desinstalando python3-selinux (3.0-1build2) ...
Desinstalando python3-xmltodict (0.12.0-1) ...
Procesando disparadores para man-db (2.9.1-1) ...
Obj:1 http://es.archive.ubuntu.com/ubuntu focal InRelease
Obj:2 http://es.archive.ubuntu.com/ubuntu focal-updates InRelease                                                              
Obj:3 https://download.docker.com/linux/ubuntu focal InRelease                                                                 
Obj:4 http://security.ubuntu.com/ubuntu focal-security InRelease                                                      
Obj:5 http://es.archive.ubuntu.com/ubuntu focal-backports InRelease                          
Obj:6 https://download.virtualbox.org/virtualbox/debian focal InRelease
Leyendo lista de paquetes... Hecho       
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
Todos los paquetes están actualizados.
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
software-properties-common ya está en su versión más reciente (0.98.9).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
python3-apt ya está en su versión más reciente (2.0.0).
python3-setuptools ya está en su versión más reciente (45.2.0-1).
python3-pip ya está en su versión más reciente (20.0.2-5ubuntu1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
yamllint ya está en su versión más reciente (1.20.0-1).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
shellcheck ya está en su versión más reciente (0.7.0-2build2).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.
\# Python3 Dependencies (install python3 ansible)
bash scripts/install_python3_dependencies.sh
Requirement already up-to-date: pip in /home/xir/.local/lib/python3.8/site-packages (20.1.1)
Requirement already up-to-date: keyrings.alt in /home/xir/.local/lib/python3.8/site-packages (3.4.0)
Requirement already up-to-date: setuptools in /home/xir/.local/lib/python3.8/site-packages (47.3.1)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.34.2)
Requirement already satisfied: ansible>=2.9.7 in /home/xir/.local/lib/python3.8/site-packages (from -r requirements_ansible.txt (line 1)) (2.9.10)
Requirement already satisfied: psutil>=5.7.0 in /home/xir/.local/lib/python3.8/site-packages (from -r requirements_ansible.txt (line 2)) (5.7.0)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from ansible>=2.9.7->-r requirements_ansible.txt (line 1)) (5.3.1)
Requirement already satisfied: jinja2 in /home/xir/.local/lib/python3.8/site-packages (from ansible>=2.9.7->-r requirements_ansible.txt (line 1)) (2.11.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from ansible>=2.9.7->-r requirements_ansible.txt (line 1)) (2.8)
Requirement already satisfied: MarkupSafe>=0.23 in /home/xir/.local/lib/python3.8/site-packages (from jinja2->ansible>=2.9.7->-r requirements_ansible.txt (line 1)) (1.1.1)
\# Ensure "$HOME/.local/bin" is part of PATH
bash scripts/before_script_path_fix.sh
\# Source folder (to ensure initial setup loads this file)
. /etc/profile
\# Check that PATH and requirements are correct
**ansible --version | grep "python version"
bash: ansible: command not found
make: *** [Makefile:82: bootstrap-check] Error 1**

**Comment by iancleary** [comment]
Hello @ieguiguren,

It seems these two portions of the script are not placing `ansible` on the PATH within this scripts runtime (especially the first run of the script). 

```bash
Requirement already satisfied: ansible>=2.9.7 in /home/xir/.local/lib/python3.8/site-packages (from -r requirements_ansible.txt (line 1)) (2.9.10)

...

# Ensure "$HOME/.local/bin" is part of PATH
bash scripts/before_script_path_fix.sh
# Source folder (to ensure initial setup loads this file)
. /etc/profile
```

I was planning the `. /etc/profile` command to correctly reload `/etc/profile.d/home-local-bin.sh`, which it might not in the initial shell session (which is a bug).

Is ansible on your PATH in a new terminal session?  

## Solution Discussion

We could force ansible within the Makefile to be `$HOME/.local/bin/ansible`, but I was hoping the path_fix script would work in the initial script.  

Another option would be to add an conditional export to add `$HOME/.local/bin/` to PATH during the script (not by calling `. /etc/profile`.

I agree it should work on the initial run of the script, without starting a new terminal/shell session.

**Comment by ieguiguren** [comment]
Hi.

Opening a new session ansible appears at $HOME/.local/bin/ansible and the $HOME/.local/bin is in the path, so may be necessary to update the PATH during the terminal session. 
![image](https://user-images.githubusercontent.com/1809729/86264693-21e69d80-bbc3-11ea-8d46-d49203d7800e.png)


I'd rather go on with solution \#2 as it is directly modifying the environment of the running shell.

Thanks for sharing. I've got a lot to tune already but I am discovering a lot of apps I didn't know about.

**Comment by iancleary** [comment]
Hi @ieguiguren,

I agree solution 2 is probably the way to go.  I'll investigate and work on a Pull Request sometime soon (I'll think about test coverage).

You're welcome! :slightly_smiling_face: I hope the apps help you out!  Please let me know if you find anything else useful you'd like to share.

Take care and stay safe!

**Comment by iancleary** [comment]
Added conditional logic to the make file and updated test coverage per https://github.com/iancleary/ansible-desktop/pull/165#issuecomment-653038539
